### ISSUE TITLE
IconSpecification crashes game with Artisanal Reskins

### ISSUE THREAD

**Issue by oorzkws** [raiguard/Factorio-EditorExtensions#20]
Opening the crafting menu crashes the game with Artisanal Reskins present. This is _not_ a reskin problem, as EE is improperly handling items without icons, but with icon_size and/or icon_mipmaps.

Minimal reproduction save and log attached.
[factorio-current.log](https://github.com/raiguard/Factorio-EditorExtensions/files/5060276/factorio-current.log)
[iconerror.zip](https://github.com/raiguard/Factorio-EditorExtensions/files/5060277/iconerror.zip)

**Comment by kirazy** [comment]
Specifically:

```LUA
function util.extract_icon_info(obj)
  return {icon=obj.icon, icon_size=obj.icon_size, icon_mipmaps=obj.icon_mipmaps}
end
```

I set `obj.icon = nil` when I set my `obj.icons` field. This function has no protection against that so produces an `icons` definition that looks like this:

```LUA
icons = {
  icon_size = 64,
  icon_mipmaps = 4,
}
```

**Comment by raiguard** [comment]
So according to the log file you sent me, the invalid definition somehow snuck its way past the data stage and crashed the game. When I loaded that save it properly crashed in the data stage, so that's weird.

Anyway, I fixed it for the next release.

![image](https://user-images.githubusercontent.com/3515394/90303027-a6d20180-de67-11ea-8091-54bba08d5092.png)

**Comment by raiguard** [comment]
The patch has been released.

**Comment by oorzkws** [comment]
Thanks for the fix
