### ISSUE TITLE
Infinity Mode migrations

### ISSUE THREAD

**Issue by RobertSchuh** [raiguard/Factorio-EditorExtensions#21]
#### Is your feature request related to a problem? Please describe.

I opened an old 0.17 map where I had used Infinity Mode. Since that mod is obsolete and this one replaces it, I switched to using this one. Unfortunately all the Infinity Mode items that I had placed in the map disappeared.

#### Describe the solution you'd like

Since most items from IM have a direct counterpart here, would it be possible to automatically migrate IM items in old maps to EE? This might not be possible with EE alone, but an update to IM with EE as dependency could maybe do it.

**Comment by raiguard** [comment]
Could you send me that save file? I don't actually have any save files left that used IM so I'm unable to test this.

**Comment by RobertSchuh** [comment]
http://www.mediafire.com/file/c0vjwxwo3bxb7k6/GreyGooMk3_7.zip/file

Here's the old savegame with Infinity Mode roboports that got deleted.

**Comment by raiguard** [comment]
So, apparently migrations don't work the way I thought they did. I had thought that my existing ones would handle this case, but apparently they don't. I added a new migration for the infinity roboport, but didn't bother with the items because the factory seems to work fine without them.

I also added code to rebuild all infinity loaders if coming from EE. I found an old map that used IM and the infinity loaders were completely borked.

Thanks for the report!
