### ISSUE TITLE
Infinite Engery tool to support decimals

### ISSUE THREAD

**Issue by billbo99** [raiguard/Factorio-EditorExtensions#32]
Any chance you "Infinite Engery tool" could support decimals ?

eg  2.3GW

I know I can put down one at 2GW and another at 300MW.

Having support for decimals would be easier is all.

**Comment by raiguard** [comment]
Implemented for a future version. Unfortunately, the next major version isn't coming until Factorio 1.1, since I am depending on a few API features that are being added in that version. But you can look forward to it!

![image](https://user-images.githubusercontent.com/3515394/95943266-8c9e9c00-0da2-11eb-9272-81b7faba386f.png)

**Comment by raiguard** [comment]
I backported the decimals feature from my 1.1 branch and released it, along with a few other new features.
